set nocompatible
set noswapfile

colorscheme plain256
highlight CursorLine cterm=bold ctermbg=Black

if &diff
  set diffopt+=iwhite
endif

if &bin
  au BufReadPost * %!xxd
  au BufWritePre * %!xxd -r
endif

" GDB integration
packadd termdebug
let g:termdebug_wide = 80

" netrw file browser tree list and no banner
let g:netrw_banner = 0
let g:netrw_liststyle = 3

set showmode
set wildmenu
set number
set list
set listchars=tab:↹∘,trail:∙
set matchpairs+=<:>
set cursorline
set colorcolumn=79

set hlsearch
set incsearch

set mouse=a

set virtualedit=all

set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

set scrolloff=9

